/// Represents a user in the Better Auth system.
///
/// The [User] class contains all user-related information returned by the
/// Better Auth API, including identity, profile data, and metadata.
///
/// Example:
/// ```dart
/// final user = User.fromJson(jsonResponse);
/// print('User: ${user.name} (${user.email})');
/// ```
///
/// See also:
/// - [Session] for authentication session information
class User {
  /// Unique user identifier.
  ///
  /// This ID is generated by the backend and uniquely identifies the user
  /// across the entire system.
  final String id;

  /// User's email address.
  ///
  /// The email is used for authentication and communication.
  final String email;

  /// User's display name.
  ///
  /// This is the name shown in the UI. May be null if not set.
  final String? name;

  /// User's profile image URL.
  ///
  /// A URL pointing to the user's avatar or profile picture.
  /// May be null if no image is set.
  final String? image;

  /// Whether the email has been verified.
  ///
  /// This flag indicates if the user has completed email verification.
  final bool emailVerified;

  /// User's role in the system.
  ///
  /// The role determines what permissions the user has.
  /// May be null if no role is assigned.
  final String? role;

  /// Timestamp when the user account was created.
  final DateTime createdAt;

  /// Timestamp when the user account was last updated.
  final DateTime updatedAt;

  /// Custom metadata associated with the user.
  ///
  /// Additional custom fields can be stored here.
  /// May be null if no metadata exists.
  final Map<String, dynamic>? metadata;

  /// Creates a new [User] instance.
  ///
  /// All parameters are required except [name], [image], [role], and [metadata].
  User({
    required this.id,
    required this.email,
    this.name,
    this.image,
    this.emailVerified = false,
    this.role,
    required this.createdAt,
    required this.updatedAt,
    this.metadata,
  });

  /// Creates a [User] instance from a JSON response.
  ///
  /// The [json] map should contain the keys as defined by the Better Auth API.
  ///
  /// Example:
  /// ```dart
  /// final user = User.fromJson({
  ///   'id': 'user_123',
  ///   'email': 'test@example.com',
  ///   'name': 'Test User',
  /// });
  /// ```
  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id'] as String,
      email: json['email'] as String,
      name: json['name'] as String?,
      image: json['image'] as String?,
      emailVerified: json['emailVerified'] as bool? ?? false,
      role: json['role'] as String?,
      createdAt: json['createdAt'] != null
          ? DateTime.parse(json['createdAt'] as String)
          : DateTime.now(),
      updatedAt: json['updatedAt'] != null
          ? DateTime.parse(json['updatedAt'] as String)
          : DateTime.now(),
      metadata: json['metadata'] as Map<String, dynamic>?,
    );
  }

  /// Converts this [User] to a JSON map.
  ///
  /// The returned map can be serialized to JSON for storage or transmission.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'email': email,
      'name': name,
      'image': image,
      'emailVerified': emailVerified,
      'role': role,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
      'metadata': metadata,
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is User && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;
}
